name: PHPunit Test

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  laravel-test:
    runs-on: ubuntu-latest
    
    # 環境変数を設定
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: ":memory:"
      APP_ENV: testing
      CACHE_DRIVER: array
      SESSION_DRIVER: array
      QUEUE_DRIVER: sync
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql, sqlite3
        coverage: none
        
    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      
    - name: Cache composer dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-
        
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      working-directory: ./src
      
    - name: Create .env file
      run: |
        cp .env.example .env
        php artisan key:generate
      working-directory: ./src
      
    - name: Run PHPunit
      id: PHPunit
      run: |
        OUTPUT=$(php artisan test 2>&1) || echo "FAILED=true" >> $GITHUB_ENV
        echo "$OUTPUT" > test_output.txt
      working-directory: ./src

    - name: Comment PR with Test Results
      if: env.FAILED == 'true'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const output = fs.readFileSync('src/test_output.txt', 'utf8');
          
          const formatComment = (output) => {
            // タイトル部分の作成
            let comment = '## PHPunit テストで問題が検出されました ⚠️\n\n';
            
            // コードブロックとして出力を追加
            comment += '```\n' + output + '\n```\n\n';
            return comment;
          };
          
          const formattedComment = formatComment(output);
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: formattedComment
          });

    - name: Fail if tests failed
      if: env.FAILED == 'true'
      run: exit 1
